name: Build and Deploy

on:
  push:
    branches: [ master ]
  # Manual activation
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Log into Docker
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.2.2
        id: docker_build
        with:
          push: true
          tags: jdanksarmy/jdanks-armyd:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
      - name: Deploy
        uses: fjogeleit/http-request-action@v1.6.1
        with:
          url: ${{ secrets.UPDATE_SVC_URL }}
          bearerToken: ${{ secrets.UPDATE_SVC_TOKEN }}
          timeout: 0
